apiVersion: v1
kind: Service
metadata:
  name: nodejs-service-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
